from __future__ import annotations

TECH_TAXONOMY: dict[str, tuple[str, ...]] = {
    "Python": ("python",),
    "TypeScript": ("typescript",),
    "JavaScript": ("javascript",),
    "C++": ("c++", "cpp"),
    "C#": ("c#", "c sharp"),
    "Java": ("java",),
    "PHP": ("php",),
    "Ruby": ("ruby",),
    "Go": ("golang", "go lang"),
    "Rust": ("rust",),
    "SQL": ("sql",),
    "React": ("react", "react.js", "reactjs"),
    "Next.js": ("next.js", "nextjs", "next js"),
    "Vite": ("vite",),
    "Tailwind": ("tailwind", "tailwindcss", "tailwind css"),
    "HTML": ("html",),
    "CSS": ("css",),
    "Vue": ("vue", "vue.js", "vuejs"),
    "Angular": ("angular",),
    "Svelte": ("svelte",),
    "Flutter": ("flutter",),
    "Swift": ("swift",),
    "Kotlin": ("kotlin",),
    "Android": ("android",),
    "iOS": ("ios", "i os"),
    "Node.js": ("node.js", "nodejs", "node js"),
    "Express": ("express", "express.js", "expressjs"),
    "NestJS": ("nestjs", "nest.js", "nest js"),
    "FastAPI": ("fastapi", "fast api"),
    "Django": ("django",),
    "Flask": ("flask",),
    "Laravel": ("laravel",),
    "Ruby on Rails": ("ruby on rails", "rails"),
    "WordPress": ("wordpress", "wp"),
    "REST API": ("rest api", "rest apis", "restful api", "restful apis", "restful", "rest endpoints", "api endpoint", "api endpoints"),
    "GraphQL": ("graphql", "graph ql"),
    "PostgreSQL": ("postgresql", "postgres", "neon postgres", "neon"),
    "MySQL": ("mysql",),
    "MongoDB": ("mongodb", "mongo"),
    "Redis": ("redis",),
    "Prisma": ("prisma",),
    "Drizzle": ("drizzle", "drizzle orm"),
    "Supabase": ("supabase",),
    "Qdrant": ("qdrant",),
    "Pinecone": ("pinecone",),
    "ChromaDB": ("chromadb", "chroma"),
    "Vector DB": ("vector database", "vector db", "vector store"),
    "RAG": ("rag", "retrieval augmented generation", "retrieval-augmented generation"),
    "LLM": ("llm", "large language model", "language model"),
    "AI Agents": ("ai agent", "ai agents", "agentic", "multi-agent", "multi agent"),
    "OpenAI": ("openai", "gpt", "chatgpt"),
    "Anthropic": ("anthropic", "claude"),
    "LangChain": ("langchain", "lang chain"),
    "LangGraph": ("langgraph", "lang graph"),
    "Machine Learning": ("machine learning", "ml engineer", "ml engineering", "ml ops", "mlops", "ml model", "ml pipeline", "ai/ml"),
    "NLP": ("nlp", "natural language processing"),
    "Computer Vision": ("computer vision", "vision model", "object detection", "image segmentation"),
    "PyTorch": ("pytorch", "torch"),
    "TensorFlow": ("tensorflow",),
    "Automation": ("automation", "workflow automation", "zapier", "n8n"),
    "Docker": ("docker", "container"),
    "Kubernetes": ("kubernetes", "k8s"),
    "Terraform": ("terraform",),
    "AWS": ("aws", "amazon web services"),
    "GCP": ("gcp", "google cloud"),
    "Azure": ("azure",),
    "Vercel": ("vercel",),
    "CI/CD": ("ci/cd", "cicd", "github actions"),
    "Linux": ("linux",),
    "WebSockets": ("websocket", "websockets", "socket.io"),
    "LiveKit": ("livekit", "livekit agents"),
    "Deepgram": ("deepgram",),
    "Groq": ("groq",),
    "Stripe": ("stripe",),
    "Firebase": ("firebase",),
    "Tauri": ("tauri",),
    "Electron": ("electron",),
    "Playwright": ("playwright",),
    "Data Pipeline": ("data pipeline", "etl", "data engineering"),
    "SAP": ("sap",),
    "ABAP": ("abap",),
    "Salesforce": ("salesforce", "apex"),
    "ServiceNow": ("servicenow", "service now"),
}


TECH_CATEGORY: dict[str, str] = {
    "Python": "language",
    "TypeScript": "language",
    "JavaScript": "language",
    "C++": "language",
    "C#": "language",
    "Java": "language",
    "PHP": "language",
    "Ruby": "language",
    "Go": "language",
    "Rust": "language",
    "SQL": "data",
    "React": "frontend",
    "Next.js": "frontend",
    "Vite": "frontend",
    "Tailwind": "frontend",
    "HTML": "frontend",
    "CSS": "frontend",
    "Vue": "frontend",
    "Angular": "frontend",
    "Svelte": "frontend",
    "Flutter": "mobile",
    "Swift": "mobile",
    "Kotlin": "mobile",
    "Android": "mobile",
    "iOS": "mobile",
    "Node.js": "backend",
    "Express": "backend",
    "NestJS": "backend",
    "FastAPI": "backend",
    "Django": "backend",
    "Flask": "backend",
    "Laravel": "backend",
    "Ruby on Rails": "backend",
    "WordPress": "cms",
    "REST API": "backend",
    "GraphQL": "backend",
    "PostgreSQL": "data",
    "MySQL": "data",
    "MongoDB": "data",
    "Redis": "data",
    "Prisma": "data",
    "Drizzle": "data",
    "Supabase": "data",
    "Qdrant": "ai",
    "Pinecone": "ai",
    "ChromaDB": "ai",
    "Vector DB": "ai",
    "RAG": "ai",
    "LLM": "ai",
    "AI Agents": "ai",
    "OpenAI": "ai",
    "Anthropic": "ai",
    "LangChain": "ai",
    "LangGraph": "ai",
    "Machine Learning": "ai",
    "NLP": "ai",
    "Computer Vision": "ai",
    "PyTorch": "ai",
    "TensorFlow": "ai",
    "Automation": "automation",
    "Docker": "infra",
    "Kubernetes": "infra",
    "Terraform": "infra",
    "AWS": "infra",
    "GCP": "infra",
    "Azure": "infra",
    "Vercel": "infra",
    "CI/CD": "infra",
    "Linux": "infra",
    "WebSockets": "backend",
    "LiveKit": "realtime",
    "Deepgram": "realtime",
    "Groq": "ai",
    "Stripe": "product",
    "Firebase": "backend",
    "Tauri": "desktop",
    "Electron": "desktop",
    "Playwright": "testing",
    "Data Pipeline": "data",
    "SAP": "enterprise",
    "ABAP": "enterprise",
    "Salesforce": "enterprise",
    "ServiceNow": "enterprise",
}
