from __future__ import annotations

from core.config import (
    DEFAULT_JOB_TARGETS,
    INDIA_JOB_TARGETS,
    BLOCKED_JOB_TARGET_MARKERS,
    dedupe_targets,
    desired_position,
    free_sources_enabled,
    has_explicit_discovery_targets,
    has_x_token,
    has_profile_discovery_signal,
    int_cfg,
    is_hn_target,
    job_market_focus,
    job_targets,
    profile_for_discovery,
    profile_free_source_targets,
    profile_x_queries,
    split_configured_targets,
    terms_for_discovery,
    truthy,
)

__all__ = [
    "BLOCKED_JOB_TARGET_MARKERS",
    "DEFAULT_JOB_TARGETS",
    "INDIA_JOB_TARGETS",
    "dedupe_targets",
    "desired_position",
    "free_sources_enabled",
    "has_explicit_discovery_targets",
    "has_profile_discovery_signal",
    "has_x_token",
    "int_cfg",
    "is_hn_target",
    "job_market_focus",
    "job_targets",
    "profile_for_discovery",
    "profile_free_source_targets",
    "profile_x_queries",
    "split_configured_targets",
    "terms_for_discovery",
    "truthy",
]
